plugins {
    id 'java'
}

group = 'org.jun'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // 그래도 로거는 최소한...
    implementation 'org.slf4j:slf4j-api:2.0.17'
    implementation 'ch.qos.logback:logback-classic:1.5.21'

    // 리플렉션은 조금 더 쉽게...
    implementation 'org.reflections:reflections:0.10.2'

    // yml 파일 리더
    implementation 'org.yaml:snakeyaml:2.5'

    // 다이나믹 프록시는 인터페이스 기반만 메소드 호출 가능
    // 그래서 클래스 기반 상속 프록시 구현하는 CGLIB 라이브러리 추가
    implementation 'cglib:cglib:3.3.0'

    // 근데 cglib는 또 jdk 버전 올라가면서 모듈 접근성 제한이 강화돼서 안됨....
    // 특히 17 이상부터 안됨.. 그래서 얘 쓰자.. 스프링은 복합적으로 쓰면서 내부적으로 라이브러리 대응까지 한다네..
    implementation 'net.bytebuddy:byte-buddy:1.18.2'
    implementation 'org.objenesis:objenesis:3.4' // 생성자를 호출하지 않고 객체를 만드는(JVM 규칙 무시 라이브러리)
}

test {
    useJUnitPlatform()
}